// <auto-generated />
using System;
using InsuranceAdministration.Infrastructure.Persistance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceAdministration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217230025_t6")]
    partial class t6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.DailyMissionEntities.DailyMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailyMissions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PolicemanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolicemanId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HasChantDriverCertificate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Policemen");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Punishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliceManId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoliceManId");

                    b.ToTable("Punishments");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.AssignmentOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingsOptionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettingsOptionsId");

                    b.ToTable("AssignmentOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.EducationLevelOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingsOptionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettingsOptionsId");

                    b.ToTable("EducationLevelOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.PoliceRankOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingsOptionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettingsOptionsId");

                    b.ToTable("PoliceRankOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SettingsOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assignment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnlistmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServiceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TripleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("TripleNumber");

                    b.ToTable("Soldier");
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoatNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyMissionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WirelessCallSign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyMissionId");

                    b.ToTable("Mission");
                });

            modelBuilder.Entity("MissionPoliceMan", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoliceManId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MissionId", "PoliceManId");

                    b.HasIndex("PoliceManId");

                    b.ToTable("MissionPoliceMan");
                });

            modelBuilder.Entity("MissionSoldier", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MissionId", "SoldierId");

                    b.HasIndex("SoldierId");

                    b.ToTable("MissionSoldier");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Leave", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", "PoliceMan")
                        .WithMany("Leaves")
                        .HasForeignKey("PolicemanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceMan");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Punishment", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", "PoliceMan")
                        .WithMany("Punishments")
                        .HasForeignKey("PoliceManId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceMan");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.AssignmentOptions", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", "SettingsOptions")
                        .WithMany()
                        .HasForeignKey("SettingsOptionsId");

                    b.Navigation("SettingsOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.EducationLevelOptions", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", "SettingsOptions")
                        .WithMany()
                        .HasForeignKey("SettingsOptionsId");

                    b.Navigation("SettingsOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.PoliceRankOptions", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", "SettingsOptions")
                        .WithMany()
                        .HasForeignKey("SettingsOptionsId");

                    b.Navigation("SettingsOptions");
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.DailyMissionEntities.DailyMission", "DailyMission")
                        .WithMany("Missions")
                        .HasForeignKey("DailyMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyMission");
                });

            modelBuilder.Entity("MissionPoliceMan", b =>
                {
                    b.HasOne("Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", null)
                        .WithMany()
                        .HasForeignKey("PoliceManId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissionSoldier", b =>
                {
                    b.HasOne("Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", null)
                        .WithMany()
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.DailyMissionEntities.DailyMission", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", b =>
                {
                    b.Navigation("Leaves");

                    b.Navigation("Punishments");
                });
#pragma warning restore 612, 618
        }
    }
}
