// <auto-generated />
using System;
using InsuranceAdministration.Infrastructure.Persistance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceAdministration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126030219_t31")]
    partial class t31
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.DailyMissionEntities.DailyMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailyMissions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PolicemanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolicemanId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HasChantDriverCertificate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Policemen");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Punishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliceManId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoliceManId");

                    b.ToTable("Punishments");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.AssignmentOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingsOptionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettingsOptionsId");

                    b.ToTable("AssignmentOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.EducationLevelOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingsOptionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettingsOptionsId");

                    b.ToTable("EducationLevelOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.MainSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConscriptsAffairsOfficerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConscriptsAffairsPoliceManName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentDirectorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MainSettings");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SettingsOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.SoldierLeaveOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettingsOptionsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SettingsOptionsId");

                    b.ToTable("SoldierLeaveOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Acquaintance.BaseFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcquaintanceDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcquaintanceDocumentId");

                    b.ToTable("BaseFamily");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Acquaintance.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcquaintanceDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseJob")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseNationalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcquaintanceDocumentId");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.AcquaintanceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId")
                        .IsUnique();

                    b.ToTable("AcquaintanceDocument");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.PoliticalAndCriminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriminalRecord")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliticalStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId")
                        .IsUnique();

                    b.ToTable("PoliticalAndCriminal");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assignment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CurrentIsLeave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnlistmentDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Job")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ServiceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TripleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("TripleNumber");

                    b.ToTable("Soldier");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.SoldierLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndPage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId");

                    b.ToTable("SoldierLeave");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraingName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoatNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DailyMissionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WirelessCallSign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyMissionId");

                    b.ToTable("Mission");
                });

            modelBuilder.Entity("MissionPoliceMan", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoliceManId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MissionId", "PoliceManId");

                    b.HasIndex("PoliceManId");

                    b.ToTable("MissionPoliceMan");
                });

            modelBuilder.Entity("MissionSoldier", b =>
                {
                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MissionId", "SoldierId");

                    b.HasIndex("SoldierId");

                    b.ToTable("MissionSoldier");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Leave", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", "PoliceMan")
                        .WithMany("Leaves")
                        .HasForeignKey("PolicemanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceMan");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.Punishment", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", "PoliceMan")
                        .WithMany("Punishments")
                        .HasForeignKey("PoliceManId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliceMan");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.AssignmentOptions", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", "SettingsOptions")
                        .WithMany()
                        .HasForeignKey("SettingsOptionsId");

                    b.Navigation("SettingsOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.EducationLevelOptions", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", "SettingsOptions")
                        .WithMany()
                        .HasForeignKey("SettingsOptionsId");

                    b.Navigation("SettingsOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.Settings.SoldierLeaveOptions", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.Settings.SettingsOptions", "SettingsOptions")
                        .WithMany()
                        .HasForeignKey("SettingsOptionsId");

                    b.Navigation("SettingsOptions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Acquaintance.BaseFamily", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.AcquaintanceDocument", "AcquaintanceDocument")
                        .WithMany("BaseFamily")
                        .HasForeignKey("AcquaintanceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcquaintanceDocument");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Acquaintance.Family", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.AcquaintanceDocument", "AcquaintanceDocument")
                        .WithMany("Family")
                        .HasForeignKey("AcquaintanceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcquaintanceDocument");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.AcquaintanceDocument", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", "Soldier")
                        .WithOne("AcquaintanceDocument")
                        .HasForeignKey("InsuranceAdministration.Core.Entities.SoldierEntities.AcquaintanceDocument", "SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.PoliticalAndCriminal", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", "Soldier")
                        .WithOne("PoliticalAndCriminal")
                        .HasForeignKey("InsuranceAdministration.Core.Entities.SoldierEntities.PoliticalAndCriminal", "SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.SoldierLeave", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", "Soldier")
                        .WithMany("Leaves")
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Training", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", "Soldier")
                        .WithMany("Trainings")
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("Mission", b =>
                {
                    b.HasOne("InsuranceAdministration.Core.Entities.DailyMissionEntities.DailyMission", "DailyMission")
                        .WithMany("Missions")
                        .HasForeignKey("DailyMissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DailyMission");
                });

            modelBuilder.Entity("MissionPoliceMan", b =>
                {
                    b.HasOne("Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", null)
                        .WithMany()
                        .HasForeignKey("PoliceManId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissionSoldier", b =>
                {
                    b.HasOne("Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", null)
                        .WithMany()
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.DailyMissionEntities.DailyMission", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.PoliceManEntities.PoliceMan", b =>
                {
                    b.Navigation("Leaves");

                    b.Navigation("Punishments");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.AcquaintanceDocument", b =>
                {
                    b.Navigation("BaseFamily");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("InsuranceAdministration.Core.Entities.SoldierEntities.Soldier", b =>
                {
                    b.Navigation("AcquaintanceDocument");

                    b.Navigation("Leaves");

                    b.Navigation("PoliticalAndCriminal");

                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
